# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_articles',
            fields=[
                ('articleID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='标题')),
                ('content_md', models.TextField(verbose_name='Markdown内容')),
                ('content_html', models.TextField(verbose_name='html内容')),
                ('abstract', models.CharField(max_length=140, verbose_name='摘要')),
                ('created', models.DateTimeField(verbose_name='创建时间')),
                ('updated', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='tb_comments',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False, verbose_name='留言ID')),
                ('content', models.CharField(max_length=140, verbose_name='留言内容')),
                ('IP', models.CharField(max_length=30, verbose_name='留言来源')),
                ('lefted', models.DateTimeField(verbose_name='留言时间')),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.tb_articles')),
            ],
        ),
        migrations.CreateModel(
            name='tb_projs',
            fields=[
                ('projID', models.AutoField(primary_key=True, serialize=False, verbose_name='作品ID')),
                ('title', models.CharField(db_index=True, max_length=24, verbose_name='作品名')),
                ('abstract', models.CharField(max_length=140, verbose_name='作品简介')),
                ('uploaded', models.DateTimeField(verbose_name='作品发布时间')),
                ('imgsURL', models.URLField(verbose_name='作品图集')),
                ('gitURL', models.URLField(default='github.com/HitBirds', verbose_name='作品GitHubURL')),
            ],
        ),
        migrations.CreateModel(
            name='tb_tags',
            fields=[
                ('name', models.CharField(max_length=24, verbose_name='分类')),
                ('articlecount', models.PositiveIntegerField(verbose_name='同类文章数量')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='正则id')),
            ],
        ),
        migrations.AddField(
            model_name='tb_articles',
            name='tagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.tb_tags'),
        ),
    ]
