# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_comments',
            old_name='leftd',
            new_name='lefted',
        ),
    ]
