# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170429_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_projs',
            name='gitURL',
            field=models.URLField(default='github.com/HitBirds', verbose_name='作品GitHubURL'),
        ),
    ]
